# Generated by Django 5.0.7 on 2024-07-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_type', models.CharField(choices=[('Payslip', 'Payslip Query'), ('Timesheet', 'Timesheet Query'), ('Roster', 'Roster Query')], max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('query_reason', models.TextField()),
                ('other_information', models.TextField()),
                ('date_of_query', models.DateField()),
                ('payslip_issue_date', models.DateField()),
                ('employee_id_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
            ],
        ),
    ]
